# Generated by Django 4.2.20 on 2025-03-21 11:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0003_movie_genres_movie_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='评分')),
                ('watch_time', models.DateTimeField(auto_now_add=True, verbose_name='观看时间')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie', verbose_name='电影')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户行为',
                'verbose_name_plural': '用户行为',
                'ordering': ['-watch_time'],
                'unique_together': {('user', 'movie')},
            },
        ),
        migrations.CreateModel(
            name='MovieSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='相似度')),
                ('movie1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to', to='movies.movie', verbose_name='电影1')),
                ('movie2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_from', to='movies.movie', verbose_name='电影2')),
            ],
            options={
                'verbose_name': '电影相似度',
                'verbose_name_plural': '电影相似度',
                'ordering': ['-similarity'],
                'unique_together': {('movie1', 'movie2')},
            },
        ),
    ]
