# Generated by Django 4.2.20 on 2025-03-21 11:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='类型名称')),
            ],
            options={
                'verbose_name': '电影类型',
                'verbose_name_plural': '电影类型',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='电影名称')),
                ('original_title', models.CharField(blank=True, max_length=200, verbose_name='原始名称')),
                ('director', models.CharField(blank=True, max_length=100, verbose_name='导演')),
                ('actors', models.CharField(blank=True, max_length=200, verbose_name='主演')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='上映日期')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='时长(分钟)')),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='评分')),
                ('rating_count', models.IntegerField(default=0, verbose_name='评分人数')),
                ('description', models.TextField(blank=True, verbose_name='剧情简介')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '电影',
                'verbose_name_plural': '电影',
                'ordering': ['-rating', '-rating_count'],
            },
        ),
        migrations.CreateModel(
            name='MovieTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, verbose_name='标签')),
                ('count', models.IntegerField(default=1, verbose_name='使用次数')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie', verbose_name='电影')),
            ],
            options={
                'verbose_name': '电影标签',
                'verbose_name_plural': '电影标签',
                'unique_together': {('movie', 'tag')},
            },
        ),
    ]
