# Generated by Django 4.2.20 on 2025-03-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_delete_movietag'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='movies', to='movies.genre', verbose_name='电影类型'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, upload_to='movie_posters/', verbose_name='海报'),
        ),
    ]
