# Generated by Django 4.2.20 on 2025-03-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_genres_movie_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieImageCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(db_index=True, unique=True, verbose_name='电影ID')),
                ('small_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='小图URL')),
                ('medium_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='中图URL')),
                ('large_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='大图URL')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '电影图片缓存',
                'verbose_name_plural': '电影图片缓存',
                'db_table': 'movie_image_cache',
            },
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['rating'], name='movies_movi_rating_8fd49a_idx'),
        ),
    ]
